feat(KFLUXMIG-294): enable the signing of out-of-tree kernel modules
Signed-off-by: Enrique Belarte Luque <ebelarte@redhat.com>

diff --git a/tasks/managed/extract-oot-kmods/tests/test-extract-kmods-from-image.yaml b/tasks/managed/extract-oot-kmods/tests/test-extract-kmods-from-image.yaml
--- a/tasks/managed/extract-oot-kmods/tests/test-extract-kmods-from-image.yaml
+++ b/tasks/managed/extract-oot-kmods/tests/test-extract-kmods-from-image.yaml
@@ -82,48 +82,48 @@ spec:
               touch "$(workspaces.input-data.path)"/kmods/mod1.ko
               touch "$(workspaces.input-data.path)"/kmods/mod2.ko
               touch "$(workspaces.input-data.path)"/manifest.json
-    - name: run-task
-      taskRef:
-        name: extract-kmods-from-image
-      params: 
-        - name: kmodsPath
-          value: kmods 
-        - name: signedKmodsPath
-          value: signed-kmods
-        - name: snapshot
-          value: my-snapshot
-      workspaces:
-        - name: input-data
-          workspace: tests-workspace
-      runAfter:
-        - setup
-    - name: check-result
-      taskSpec:
-        workspaces:
-          - name: input-data
-        steps:
-          - name: check-values
-            image: quay.io/konflux-ci/release-service-utils:0f82be4be43294b6a96846d87ef7f7c0b9e34267
-            script: |
-              #!/usr/bin/env bash
-              set -eux
-
-              if [ -e "$(workspaces.input-data.path)/kmods/mod1.ko" ] && \
-                 [ -e "$(workspaces.input-data.path)/kmods/mod2.ko" ]; then
-                echo "Both kmod files were extracted"
-              else
-                echo "ERR: Modules could not be extracted"
-                exit 1
-              fi
-      params:
-        - name: kmodsPath
-          value: kmods
-        - name: signedKmodsPath
-          value: signed-kmods
-        - name: snapshot
-          value: my-snapshot
-      workspaces:
-        - name: input-data
-          workspace: tests-workspace
-      runAfter:
-        - run-task
+          - name: run-task
+            taskRef:
+              name: extract-kmods-from-image
+            params: 
+              - name: kmodsPath
+                value: kmods 
+              - name: signedKmodsPath
+                value: signed-kmods
+              - name: snapshot
+                value: my-snapshot
+            workspaces:
+              - name: input-data
+                workspace: tests-workspace
+            runAfter:
+              - setup
+          - name: check-result
+            taskSpec:
+              workspaces:
+                - name: input-data
+              steps:
+                - name: check-values
+                  image: quay.io/konflux-ci/release-service-utils:0f82be4be43294b6a96846d87ef7f7c0b9e34267
+                  script: |
+                    #!/usr/bin/env bash
+                    set -eux
+       
+                    if [ -e "$(workspaces.input-data.path)/kmods/mod1.ko" ] && \
+                       [ -e "$(workspaces.input-data.path)/kmods/mod2.ko" ]; then
+                      echo "Both kmod files were extracted"
+                    else
+                      echo "ERR: Modules could not be extracted"
+                      exit 1
+                    fi
+            params:
+              - name: kmodsPath
+                value: kmods
+              - name: signedKmodsPath
+                value: signed-kmods
+              - name: snapshot
+                value: my-snapshot
+            workspaces:
+              - name: input-data
+                workspace: tests-workspace
+            runAfter:
+              - run-task
